### ISSUE TITLE
copy of guest_images fails

### ISSUE THREAD

**Issue by therealcreynold** [redhat-kejones/ht#10]
TASK [overcloud : copy guest_images to Undercloud] ******************************************************************************************************************************************************************************************
Friday 17 January 2020  16:50:47 -0500 (0:00:00.389)       1:56:47.193 ******** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [director]: FAILED! => {
    "changed": false
}

MSG:

Could not find or access 'guest_images/'
Searched in:
        /home/creynold/src/hattrick/playbooks/roles/overcloud/files/guest_images/
        /home/creynold/src/hattrick/playbooks/roles/overcloud/guest_images/
        /home/creynold/src/hattrick/playbooks/roles/overcloud/tasks/files/guest_images/
        /home/creynold/src/hattrick/playbooks/roles/overcloud/tasks/guest_images/
        /home/creynold/src/hattrick/playbooks/hattrick/files/guest_images/
        /home/creynold/src/hattrick/playbooks/hattrick/guest_images/ on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option

**Comment by kjw3** [comment]
Added a placeholder guest_images folder in the hattrick repo in commit 23ddc78e6e66a8ed853850430d92cff4d834d290

Also added prompt to make user confirm that the image files that are defined in the dictionary are in place in hattrick/guest_images on the Ansible host
