### ISSUE TITLE
ansible-host-setup fails

### ISSUE THREAD

**Issue by rhcreynold** [redhat-kejones/ht#11]
TASK [Install packages] **************************************************************************************************************************************************************************************
Sunday 19 January 2020  09:34:04 -0500 (0:00:01.329)       0:00:01.426 ********
fatal: [localhost]: FAILED! => {
    "changed": false,
    "rc": 1,
    "results": [
        "git-1.8.3.1-20.el7.x86_64 providing git is already installed",
        "Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-\n              : manager\nResolving Dependencies\n--> Running transaction check\n---> Package gcc.x86_64 0:4.8.5-39.el7 will be installed\n--> Processing Dependency: cpp = 4.8.5-39.el7 for package: gcc-4.8.5-39.el7.x86_64\n--> Processing Dependency: glibc-devel >= 2.2.90-12 for package: gcc-4.8.5-39.el7.x86_64\n--> Processing Dependency: libmpc.so.3()(64bit) for package: gcc-4.8.5-39.el7.x86_64\n--> Processing Dependency: libmpfr.so.4()(64bit) for package: gcc-4.8.5-39.el7.x86_64\n---> Package libcurl-devel.x86_64 0:7.29.0-54.el7_7.1 will be installed\n---> Package libxml2-devel.x86_64 0:2.9.1-6.el7_2.3 will be installed\n--> Processing Dependency: xz-devel for package: libxml2-devel-2.9.1-6.el7_2.3.x86_64\n--> Processing Dependency: zlib-devel for package: libxml2-devel-2.9.1-6.el7_2.3.x86_64\n---> Package openssl-devel.x86_64 1:1.0.2k-19.el7 will be installed\n--> Processing Dependency: krb5-devel(x86-64) for package: 1:openssl-devel-1.0.2k-19.el7.x86_64\n---> Package python3-devel.x86_64 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python(abi) = 3.6 for package: python3-devel-3.6.8-13.el7.x86_64\n--> Processing Dependency: python3 = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n--> Processing Dependency: python-rpm-macros for package: python3-devel-3.6.8-13.el7.x86_64\n--> Processing Dependency: python3-rpm-generators for package: python3-devel-3.6.8-13.el7.x86_64\n--> Processing Dependency: python3-rpm-macros for package: python3-devel-3.6.8-13.el7.x86_64\n--> Processing Dependency: redhat-rpm-config for package: python3-devel-3.6.8-13.el7.x86_64\n--> Processing Dependency: libpython3.6m.so.1.0()(64bit) for package: python3-devel-3.6.8-13.el7.x86_64\n---> Package python3-pip.noarch 0:9.0.3-5.el7 will be installed\n--> Processing Dependency: python3-setuptools for package: python3-pip-9.0.3-5.el7.noarch\n---> Package tmux.x86_64 0:1.8-4.el7 will be installed\n--> Running transaction check\n---> Package cpp.x86_64 0:4.8.5-39.el7 will be installed\n---> Package glibc-devel.x86_64 0:2.17-292.el7 will be installed\n--> Processing Dependency: glibc-headers = 2.17-292.el7 for package: glibc-devel-2.17-292.el7.x86_64\n--> Processing Dependency: glibc-headers for package: glibc-devel-2.17-292.el7.x86_64\n---> Package krb5-devel.x86_64 0:1.15.1-37.el7_7.2 will be installed\n--> Processing Dependency: libkadm5(x86-64) = 1.15.1-37.el7_7.2 for package: krb5-devel-1.15.1-37.el7_7.2.x86_64\n--> Processing Dependency: keyutils-libs-devel for package: krb5-devel-1.15.1-37.el7_7.2.x86_64\n--> Processing Dependency: libcom_err-devel for package: krb5-devel-1.15.1-37.el7_7.2.x86_64\n--> Processing Dependency: libselinux-devel for package: krb5-devel-1.15.1-37.el7_7.2.x86_64\n--> Processing Dependency: libverto-devel for package: krb5-devel-1.15.1-37.el7_7.2.x86_64\n---> Package libmpc.x86_64 0:1.0.1-3.el7 will be installed\n---> Package mpfr.x86_64 0:3.1.1-4.el7 will be installed\n---> Package python-rpm-macros.noarch 0:3-32.el7 will be installed\n--> Processing Dependency: python-srpm-macros for package: python-rpm-macros-3-32.el7.noarch\n---> Package python3.i686 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-32) = 3.6.8-13.el7 for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libc.so.6 for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libc.so.6(GLIBC_2.0) for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libc.so.6(GLIBC_2.3.4) for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libdl.so.2 for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libm.so.6 for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libpthread.so.0 for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libpython3.6m.so.1.0 for package: python3-3.6.8-13.el7.i686\n--> Processing Dependency: libutil.so.1 for package: python3-3.6.8-13.el7.i686\n---> Package python3-devel.x86_64 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n---> Package python3-libs.x86_64 0:3.6.8-10.el7 will be installed\n---> Package python3-rpm-generators.noarch 0:6-2.el7 will be installed\n---> Package python3-rpm-macros.noarch 0:3-32.el7 will be installed\n---> Package python3-setuptools.noarch 0:39.2.0-10.el7 will be installed\n---> Package redhat-rpm-config.noarch 0:9.1.0-88.el7 will be installed\n--> Processing Dependency: dwz >= 0.4 for package: redhat-rpm-config-9.1.0-88.el7.noarch\n--> Processing Dependency: perl-srpm-macros for package: redhat-rpm-config-9.1.0-88.el7.noarch\n---> Package xz-devel.x86_64 0:5.2.2-1.el7 will be installed\n---> Package zlib-devel.x86_64 0:1.2.7-18.el7 will be installed\n--> Running transaction check\n---> Package dwz.x86_64 0:0.11-3.el7 will be installed\n---> Package glibc.i686 0:2.17-292.el7 will be installed\n--> Processing Dependency: libfreebl3.so for package: glibc-2.17-292.el7.i686\n--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-292.el7.i686\n---> Package glibc-headers.x86_64 0:2.17-292.el7 will be installed\n--> Processing Dependency: kernel-headers >= 2.2.1 for package: glibc-headers-2.17-292.el7.x86_64\n--> Processing Dependency: kernel-headers for package: glibc-headers-2.17-292.el7.x86_64\n---> Package keyutils-libs-devel.x86_64 0:1.5.8-3.el7 will be installed\n---> Package libcom_err-devel.x86_64 0:1.42.9-16.el7 will be installed\n---> Package libkadm5.x86_64 0:1.15.1-37.el7_7.2 will be installed\n---> Package libselinux-devel.x86_64 0:2.5-14.1.el7 will be installed\n--> Processing Dependency: libsepol-devel(x86-64) >= 2.5-10 for package: libselinux-devel-2.5-14.1.el7.x86_64\n--> Processing Dependency: pkgconfig(libpcre) for package: libselinux-devel-2.5-14.1.el7.x86_64\n--> Processing Dependency: pkgconfig(libsepol) for package: libselinux-devel-2.5-14.1.el7.x86_64\n---> Package libverto-devel.x86_64 0:0.2.5-4.el7 will be installed\n---> Package perl-srpm-macros.noarch 0:1-8.el7 will be installed\n---> Package python-srpm-macros.noarch 0:3-32.el7 will be installed\n---> Package python3.i686 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-32) = 3.6.8-13.el7 for package: python3-3.6.8-13.el7.i686\n---> Package python3-devel.x86_64 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n---> Package python3-libs.i686 0:3.6.8-10.el7 will be installed\n--> Processing Dependency: libbz2.so.1 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libcrypto.so.10 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libcrypto.so.10(OPENSSL_1.0.1_EC) for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libcrypto.so.10(OPENSSL_1.0.2) for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libcrypto.so.10(libcrypto.so.10) for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libexpat.so.1 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libffi.so.6 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libgdbm.so.4 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libgdbm_compat.so.4 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: liblzma.so.5 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: liblzma.so.5(XZ_5.0) for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libncursesw.so.5 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libpanelw.so.5 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libreadline.so.6 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libsqlite3.so.0 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libssl.so.10 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libssl.so.10(libssl.so.10) for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libtinfo.so.5 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libtirpc.so.1 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libz.so.1 for package: python3-libs-3.6.8-10.el7.i686\n--> Processing Dependency: libz.so.1(ZLIB_1.2.0) for package: python3-libs-3.6.8-10.el7.i686\n--> Running transaction check\n---> Package bzip2-libs.i686 0:1.0.6-13.el7 will be installed\n---> Package expat.i686 0:2.1.0-10.el7_3 will be installed\n---> Package gdbm.i686 0:1.10-8.el7 will be installed\n---> Package kernel-headers.x86_64 0:3.10.0-1062.9.1.el7 will be installed\n---> Package libffi.i686 0:3.0.13-18.el7 will be installed\n---> Package libsepol-devel.x86_64 0:2.5-10.el7 will be installed\n---> Package libtirpc.i686 0:0.2.4-0.16.el7 will be installed\n--> Processing Dependency: libcom_err.so.2 for package: libtirpc-0.2.4-0.16.el7.i686\n--> Processing Dependency: libgssapi_krb5.so.2 for package: libtirpc-0.2.4-0.16.el7.i686\n--> Processing Dependency: libgssapi_krb5.so.2(gssapi_krb5_2_MIT) for package: libtirpc-0.2.4-0.16.el7.i686\n--> Processing Dependency: libk5crypto.so.3 for package: libtirpc-0.2.4-0.16.el7.i686\n--> Processing Dependency: libkrb5.so.3 for package: libtirpc-0.2.4-0.16.el7.i686\n---> Package ncurses-libs.i686 0:5.9-14.20130511.el7_4 will be installed\n--> Processing Dependency: libgcc_s.so.1 for package: ncurses-libs-5.9-14.20130511.el7_4.i686\n--> Processing Dependency: libgcc_s.so.1(GCC_3.0) for package: ncurses-libs-5.9-14.20130511.el7_4.i686\n--> Processing Dependency: libstdc++.so.6 for package: ncurses-libs-5.9-14.20130511.el7_4.i686\n--> Processing Dependency: libstdc++.so.6(CXXABI_1.3) for package: ncurses-libs-5.9-14.20130511.el7_4.i686\n--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4) for package: ncurses-libs-5.9-14.20130511.el7_4.i686\n---> Package nss-softokn-freebl.i686 0:3.44.0-8.el7_7 will be installed\n---> Package openssl-libs.i686 1:1.0.2k-19.el7 will be installed\n---> Package pcre-devel.x86_64 0:8.32-17.el7 will be installed\n---> Package python3.i686 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-32) = 3.6.8-13.el7 for package: python3-3.6.8-13.el7.i686\n---> Package python3-devel.x86_64 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n---> Package readline.i686 0:6.2-11.el7 will be installed\n---> Package sqlite.i686 0:3.7.17-8.el7 will be installed\n---> Package xz-libs.i686 0:5.2.2-1.el7 will be installed\n---> Package zlib.i686 0:1.2.7-18.el7 will be installed\n--> Running transaction check\n---> Package krb5-libs.i686 0:1.15.1-37.el7_7.2 will be installed\n--> Processing Dependency: libkeyutils.so.1 for package: krb5-libs-1.15.1-37.el7_7.2.i686\n--> Processing Dependency: libkeyutils.so.1(KEYUTILS_0.3) for package: krb5-libs-1.15.1-37.el7_7.2.i686\n--> Processing Dependency: libkeyutils.so.1(KEYUTILS_1.0) for package: krb5-libs-1.15.1-37.el7_7.2.i686\n--> Processing Dependency: libkeyutils.so.1(KEYUTILS_1.5) for package: krb5-libs-1.15.1-37.el7_7.2.i686\n--> Processing Dependency: libselinux.so.1 for package: krb5-libs-1.15.1-37.el7_7.2.i686\n--> Processing Dependency: libverto.so.1 for package: krb5-libs-1.15.1-37.el7_7.2.i686\n---> Package libcom_err.i686 0:1.42.9-16.el7 will be installed\n---> Package libgcc.i686 0:4.8.5-39.el7 will be installed\n---> Package libstdc++.i686 0:4.8.5-39.el7 will be installed\n---> Package python3.i686 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-32) = 3.6.8-13.el7 for package: python3-3.6.8-13.el7.i686\n---> Package python3-devel.x86_64 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n--> Running transaction check\n---> Package keyutils-libs.i686 0:1.5.8-3.el7 will be installed\n---> Package libselinux.i686 0:2.5-14.1.el7 will be installed\n--> Processing Dependency: libsepol(x86-32) >= 2.5-10 for package: libselinux-2.5-14.1.el7.i686\n--> Processing Dependency: libpcre.so.1 for package: libselinux-2.5-14.1.el7.i686\n--> Processing Dependency: libsepol.so.1 for package: libselinux-2.5-14.1.el7.i686\n--> Processing Dependency: libsepol.so.1(LIBSEPOL_1.0) for package: libselinux-2.5-14.1.el7.i686\n---> Package libverto.i686 0:0.2.5-4.el7 will be installed\n---> Package python3.i686 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-32) = 3.6.8-13.el7 for package: python3-3.6.8-13.el7.i686\n---> Package python3-devel.x86_64 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n--> Running transaction check\n---> Package libsepol.i686 0:2.5-10.el7 will be installed\n---> Package pcre.i686 0:8.32-17.el7 will be installed\n---> Package python3.i686 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-32) = 3.6.8-13.el7 for package: python3-3.6.8-13.el7.i686\n---> Package python3-devel.x86_64 0:3.6.8-13.el7 will be installed\n--> Processing Dependency: python3-libs(x86-64) = 3.6.8-13.el7 for package: python3-devel-3.6.8-13.el7.x86_64\n--> Finished Dependency Resolution\nError: Package: python3-3.6.8-13.el7.i686 (rhel-7-server-optional-beta-rpms)\n           Requires: python3-libs(x86-32) = 3.6.8-13.el7\n           Available: python3-libs-3.6.8-10.el7.i686 (rhel-7-server-rpms)\n               python3-libs(x86-32) = 3.6.8-10.el7\nError: Package: python3-devel-3.6.8-13.el7.x86_64 (rhel-7-server-optional-beta-rpms)\n           Requires: python3-libs(x86-64) = 3.6.8-13.el7\n           Available: python3-libs-3.6.8-10.el7.x86_64 (rhel-7-server-rpms)\n               python3-libs(x86-64) = 3.6.8-10.el7\nError: Package: python3-devel-3.6.8-13.el7.x86_64 (rhel-7-server-optional-beta-rpms)\n           Requires: python3-libs(x86-64) = 3.6.8-13.el7\n           Installing: python3-libs-3.6.8-10.el7.x86_64 (rhel-7-server-rpms)\n               python3-libs(x86-64) = 3.6.8-10.el7\nError: Package: python3-3.6.8-13.el7.i686 (rhel-7-server-optional-beta-rpms)\n           Requires: python3-libs(x86-32) = 3.6.8-13.el7\n           Installing: python3-libs-3.6.8-10.el7.i686 (rhel-7-server-rpms)\n               python3-libs(x86-32) = 3.6.8-10.el7\n**********************************************************************\nyum can be configured to try to resolve such errors by temporarily enabling\ndisabled repos and searching for missing dependencies.\nTo enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf\n**********************************************************************\n\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"
    ]
}

MSG:

Error: Package: python3-3.6.8-13.el7.i686 (rhel-7-server-optional-beta-rpms)
           Requires: python3-libs(x86-32) = 3.6.8-13.el7
           Available: python3-libs-3.6.8-10.el7.i686 (rhel-7-server-rpms)
               python3-libs(x86-32) = 3.6.8-10.el7
Error: Package: python3-devel-3.6.8-13.el7.x86_64 (rhel-7-server-optional-beta-rpms)
           Requires: python3-libs(x86-64) = 3.6.8-13.el7
           Available: python3-libs-3.6.8-10.el7.x86_64 (rhel-7-server-rpms)
               python3-libs(x86-64) = 3.6.8-10.el7
Error: Package: python3-devel-3.6.8-13.el7.x86_64 (rhel-7-server-optional-beta-rpms)
           Requires: python3-libs(x86-64) = 3.6.8-13.el7
           Installing: python3-libs-3.6.8-10.el7.x86_64 (rhel-7-server-rpms)
               python3-libs(x86-64) = 3.6.8-10.el7
Error: Package: python3-3.6.8-13.el7.i686 (rhel-7-server-optional-beta-rpms)
           Requires: python3-libs(x86-32) = 3.6.8-13.el7
           Installing: python3-libs-3.6.8-10.el7.i686 (rhel-7-server-rpms)
               python3-libs(x86-32) = 3.6.8-10.el7

**Comment by kjw3** [comment]
Fixed by requiring standard RHEL repos. For some reason the rpm package search had said python3-devel was only available in optional-beta.

Tested on RHEL 7.7, CentOS 7 and Fedora 31 now.

There is an issue with RHEL 7 and the yum module that has it looping over API calls to the Red Hat CDN which causes slowness on tasks that use package or yum modules. Issue submitted for that on yum module
